version: '3'
services:
  portfolio:
    image: ghcr.io/zoogies/portfolio:main 
    ports:
      - 3000:3000
    networks:
      - nginx_default
    
    restart: unless-stopped

networks:
  nginx_default:
    external: true